
import { FAQItem, CountryInfo, Language } from './types';

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇱🇰' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'auto', name: 'Other', nativeName: 'Auto Detect', flag: '🌍' },
];

/**
 * Comprehensive list of 180+ countries supported for regional scam analysis.
 */
export const COUNTRIES: CountryInfo[] = [
  { name: 'India', code: 'IN', region: 'Asia', flag: '🇮🇳' },
  { name: 'United States', code: 'US', region: 'Americas', flag: '🇺🇸' },
  { name: 'United Kingdom', code: 'GB', region: 'Europe', flag: '🇬🇧' },
  { name: 'Canada', code: 'CA', region: 'Americas', flag: '🇨🇦' },
  { name: 'Australia', code: 'AU', region: 'Oceania', flag: '🇦🇺' },
  { name: 'Singapore', code: 'SG', region: 'Asia', flag: '🇸🇬' },
  { name: 'Germany', code: 'DE', region: 'Europe', flag: '🇩🇪' },
  { name: 'France', code: 'FR', region: 'Europe', flag: '🇫🇷' },
  { name: 'Japan', code: 'JP', region: 'Asia', flag: '🇯🇵' },
  { name: 'Afghanistan', code: 'AF', region: 'Asia', flag: '🇦🇫' },
  { name: 'Albania', code: 'AL', region: 'Europe', flag: '🇦🇱' },
  { name: 'Algeria', code: 'DZ', region: 'Africa', flag: '🇩🇿' },
  { name: 'Andorra', code: 'AD', region: 'Europe', flag: '🇦🇩' },
  { name: 'Angola', code: 'AO', region: 'Africa', flag: '🇦🇴' },
  { name: 'Argentina', code: 'AR', region: 'Americas', flag: '🇦🇷' },
  { name: 'Armenia', code: 'AM', region: 'Asia', flag: '🇦🇲' },
  { name: 'Austria', code: 'AT', region: 'Europe', flag: '🇦🇹' },
  { name: 'Azerbaijan', code: 'AZ', region: 'Asia', flag: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', region: 'Americas', flag: '🇧🇸' },
  { name: 'Bahrain', code: 'BH', region: 'Asia', flag: '🇧🇭' },
  { name: 'Bangladesh', code: 'BD', region: 'Asia', flag: '🇧🇩' },
  { name: 'Barbados', code: 'BB', region: 'Americas', flag: '🇧🇧' },
  { name: 'Belarus', code: 'BY', region: 'Europe', flag: '🇧🇾' },
  { name: 'Belgium', code: 'BE', region: 'Europe', flag: '🇧🇪' },
  { name: 'Belize', code: 'BZ', region: 'Americas', flag: '🇧🇿' },
  { name: 'Benin', code: 'BJ', region: 'Africa', flag: '🇧🇯' },
  { name: 'Bhutan', code: 'BT', region: 'Asia', flag: '🇧🇹' },
  { name: 'Bolivia', code: 'BO', region: 'Americas', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: 'BA', region: 'Europe', flag: '🇧🇦' },
  { name: 'Botswana', code: 'BW', region: 'Africa', flag: '🇧🇼' },
  { name: 'Brazil', code: 'BR', region: 'Americas', flag: '🇧🇷' },
  { name: 'Brunei', code: 'BN', region: 'Asia', flag: '🇧🇳' },
  { name: 'Bulgaria', code: 'BG', region: 'Europe', flag: '🇧🇬' },
  { name: 'Burkina Faso', code: 'BF', region: 'Africa', flag: '🇧🇫' },
  { name: 'Burundi', code: 'BI', region: 'Africa', flag: '🇧🇮' },
  { name: 'Cambodia', code: 'KH', region: 'Asia', flag: '🇰🇭' },
  { name: 'Cameroon', code: 'CM', region: 'Africa', flag: '🇨🇲' },
  { name: 'Cape Verde', code: 'CV', region: 'Africa', flag: '🇨🇻' },
  { name: 'Central African Republic', code: 'CF', region: 'Africa', flag: '🇨🇫' },
  { name: 'Chad', code: 'TD', region: 'Africa', flag: '🇹🇩' },
  { name: 'Chile', code: 'CL', region: 'Americas', flag: '🇨🇱' },
  { name: 'China', code: 'CN', region: 'Asia', flag: '🇨🇳' },
  { name: 'Colombia', code: 'CO', region: 'Americas', flag: '🇨🇴' },
  { name: 'Comoros', code: 'KM', region: 'Africa', flag: '🇰🇲' },
  { name: 'Congo', code: 'CG', region: 'Africa', flag: '🇨🇬' },
  { name: 'Costa Rica', code: 'CR', region: 'Americas', flag: '🇨🇷' },
  { name: 'Croatia', code: 'HR', region: 'Europe', flag: '🇭🇷' },
  { name: 'Cuba', code: 'CU', region: 'Americas', flag: '🇨🇺' },
  { name: 'Cyprus', code: 'CY', region: 'Asia', flag: '🇨🇾' },
  { name: 'Czech Republic', code: 'CZ', region: 'Europe', flag: '🇨🇿' },
  { name: 'Denmark', code: 'DK', region: 'Europe', flag: '🇩🇰' },
  { name: 'Djibouti', code: 'DJ', region: 'Africa', flag: '🇩🇯' },
  { name: 'Dominica', code: 'DM', region: 'Americas', flag: '🇩🇲' },
  { name: 'Dominican Republic', code: 'DO', region: 'Americas', flag: '🇩🇴' },
  { name: 'Ecuador', code: 'EC', region: 'Americas', flag: '🇪🇨' },
  { name: 'Egypt', code: 'EG', region: 'Africa', flag: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', region: 'Americas', flag: '🇸🇻' },
  { name: 'Equatorial Guinea', code: 'GQ', region: 'Africa', flag: '🇬🇶' },
  { name: 'Eritrea', code: 'ER', region: 'Africa', flag: '🇪🇷' },
  { name: 'Estonia', code: 'EE', region: 'Europe', flag: '🇪🇪' },
  { name: 'Eswatini', code: 'SZ', region: 'Africa', flag: '🇸🇿' },
  { name: 'Ethiopia', code: 'ET', region: 'Africa', flag: '🇪🇹' },
  { name: 'Fiji', code: 'FJ', region: 'Oceania', flag: '🇫🇯' },
  { name: 'Finland', code: 'FI', region: 'Europe', flag: '🇫🇮' },
  { name: 'Gabon', code: 'GA', region: 'Africa', flag: '🇬🇦' },
  { name: 'Gambia', code: 'GM', region: 'Africa', flag: '🇬🇲' },
  { name: 'Georgia', code: 'GE', region: 'Asia', flag: '🇬🇪' },
  { name: 'Ghana', code: 'GH', region: 'Africa', flag: '🇬🇭' },
  { name: 'Greece', code: 'GR', region: 'Europe', flag: '🇬🇷' },
  { name: 'Grenada', code: 'GD', region: 'Americas', flag: '🇬🇩' },
  { name: 'Guatemala', code: 'GT', region: 'Americas', flag: '🇬🇹' },
  { name: 'Guinea', code: 'GN', region: 'Africa', flag: '🇬🇳' },
  { name: 'Guyana', code: 'GY', region: 'Americas', flag: '🇬🇾' },
  { name: 'Haiti', code: 'HT', region: 'Americas', flag: '🇭🇹' },
  { name: 'Honduras', code: 'HN', region: 'Americas', flag: '🇭🇳' },
  { name: 'Hungary', code: 'HU', region: 'Europe', flag: '🇭🇺' },
  { name: 'Iceland', code: 'IS', region: 'Europe', flag: '🇮🇸' },
  { name: 'Indonesia', code: 'ID', region: 'Asia', flag: '🇮🇩' },
  { name: 'Iran', code: 'IR', region: 'Asia', flag: '🇮🇷' },
  { name: 'Iraq', code: 'IQ', region: 'Asia', flag: '🇮🇶' },
  { name: 'Ireland', code: 'IE', region: 'Europe', flag: '🇮🇪' },
  { name: 'Israel', code: 'IL', region: 'Asia', flag: '🇮🇱' },
  { name: 'Italy', code: 'IT', region: 'Europe', flag: '🇮🇹' },
  { name: 'Jamaica', code: 'JM', region: 'Americas', flag: '🇯🇲' },
  { name: 'Jordan', code: 'JO', region: 'Asia', flag: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KZ', region: 'Asia', flag: '🇰🇿' },
  { name: 'Kenya', code: 'KE', region: 'Africa', flag: '🇰🇪' },
  { name: 'Kiribati', code: 'KI', region: 'Oceania', flag: '🇰🇮' },
  { name: 'Kuwait', code: 'KW', region: 'Asia', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KG', region: 'Asia', flag: '🇰🇬' },
  { name: 'Laos', code: 'LA', region: 'Asia', flag: '🇱🇦' },
  { name: 'Latvia', code: 'LV', region: 'Europe', flag: '🇱🇻' },
  { name: 'Lebanon', code: 'LB', region: 'Asia', flag: '🇱🇧' },
  { name: 'Lesotho', code: 'LS', region: 'Africa', flag: '🇱🇸' },
  { name: 'Liberia', code: 'LR', region: 'Africa', flag: '🇱🇷' },
  { name: 'Libya', code: 'LY', region: 'Africa', flag: '🇱🇾' },
  { name: 'Liechtenstein', code: 'LI', region: 'Europe', flag: '🇱🇮' },
  { name: 'Lithuania', code: 'LT', region: 'Europe', flag: '🇱🇹' },
  { name: 'Luxembourg', code: 'LU', region: 'Europe', flag: '🇱🇺' },
  { name: 'Madagascar', code: 'MG', region: 'Africa', flag: '🇲🇬' },
  { name: 'Malawi', code: 'MW', region: 'Africa', flag: '🇲🇼' },
  { name: 'Malaysia', code: 'MY', region: 'Asia', flag: '🇲🇾' },
  { name: 'Maldives', code: 'MV', region: 'Asia', flag: '🇲🇻' },
  { name: 'Mali', code: 'ML', region: 'Africa', flag: '🇲🇱' },
  { name: 'Malta', code: 'MT', region: 'Europe', flag: '🇲🇹' },
  { name: 'Mauritania', code: 'MR', region: 'Africa', flag: '🇲🇷' },
  { name: 'Mauritius', code: 'MU', region: 'Africa', flag: '🇲🇺' },
  { name: 'Mexico', code: 'MX', region: 'Americas', flag: '🇲🇽' },
  { name: 'Micronesia', code: 'FM', region: 'Oceania', flag: '🇫🇲' },
  { name: 'Moldova', code: 'MD', region: 'Europe', flag: '🇲🇩' },
  { name: 'Monaco', code: 'MC', region: 'Europe', flag: '🇲🇨' },
  { name: 'Mongolia', code: 'MN', region: 'Asia', flag: '🇲🇳' },
  { name: 'Montenegro', code: 'ME', region: 'Europe', flag: '🇲🇪' },
  { name: 'Morocco', code: 'MA', region: 'Africa', flag: '🇲🇦' },
  { name: 'Mozambique', code: 'MZ', region: 'Africa', flag: '🇲🇿' },
  { name: 'Myanmar', code: 'MM', region: 'Asia', flag: '🇲🇲' },
  { name: 'Namibia', code: 'NA', region: 'Africa', flag: '🇳🇦' },
  { name: 'Nauru', code: 'NR', region: 'Oceania', flag: '🇳🇷' },
  { name: 'Nepal', code: 'NP', region: 'Asia', flag: '🇳🇵' },
  { name: 'Netherlands', code: 'NL', region: 'Europe', flag: '🇳🇱' },
  { name: 'New Zealand', code: 'NZ', region: 'Oceania', flag: '🇳🇿' },
  { name: 'Nicaragua', code: 'NI', region: 'Americas', flag: '🇳🇮' },
  { name: 'Niger', code: 'NE', region: 'Africa', flag: '🇳🇪' },
  { name: 'Nigeria', code: 'NG', region: 'Africa', flag: '🇳🇬' },
  { name: 'North Korea', code: 'KP', region: 'Asia', flag: '🇰🇵' },
  { name: 'North Macedonia', code: 'MK', region: 'Europe', flag: '🇲🇰' },
  { name: 'Norway', code: 'NO', region: 'Europe', flag: '🇳🇴' },
  { name: 'Oman', code: 'OM', region: 'Asia', flag: '🇴🇲' },
  { name: 'Pakistan', code: 'PK', region: 'Asia', flag: '🇵🇰' },
  { name: 'Palau', code: 'PW', region: 'Oceania', flag: '🇵🇼' },
  { name: 'Palestine', code: 'PS', region: 'Asia', flag: '🇵🇸' },
  { name: 'Panama', code: 'PA', region: 'Americas', flag: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'PG', region: 'Oceania', flag: '🇵🇬' },
  { name: 'Paraguay', code: 'PY', region: 'Americas', flag: '🇵🇾' },
  { name: 'Peru', code: 'PE', region: 'Americas', flag: '🇵🇪' },
  { name: 'Philippines', code: 'PH', region: 'Asia', flag: '🇵🇭' },
  { name: 'Poland', code: 'PL', region: 'Europe', flag: '🇵🇱' },
  { name: 'Portugal', code: 'PT', region: 'Europe', flag: '🇵🇹' },
  { name: 'Qatar', code: 'QA', region: 'Asia', flag: '🇶🇦' },
  { name: 'Romania', code: 'RO', region: 'Europe', flag: '🇷🇴' },
  { name: 'Russia', code: 'RU', region: 'Europe/Asia', flag: '🇷🇺' },
  { name: 'Rwanda', code: 'RW', region: 'Africa', flag: '🇷🇼' },
  { name: 'Saint Kitts and Nevis', code: 'KN', region: 'Americas', flag: '🇰🇳' },
  { name: 'Saint Lucia', code: 'LC', region: 'Americas', flag: '🇱🇨' },
  { name: 'Saint Vincent', code: 'VC', region: 'Americas', flag: '🇻🇨' },
  { name: 'Samoa', code: 'WS', region: 'Oceania', flag: '🇼🇸' },
  { name: 'San Marino', code: 'SM', region: 'Europe', flag: '🇸🇲' },
  { name: 'Sao Tome and Principe', code: 'ST', region: 'Africa', flag: '🇸🇹' },
  { name: 'Saudi Arabia', code: 'SA', region: 'Asia', flag: '🇸🇦' },
  { name: 'Senegal', code: 'SN', region: 'Africa', flag: '🇸🇳' },
  { name: 'Serbia', code: 'RS', region: 'Europe', flag: '🇷🇸' },
  { name: 'Seychelles', code: 'SC', region: 'Africa', flag: '🇸🇨' },
  { name: 'Sierra Leone', code: 'SL', region: 'Africa', flag: '🇸🇱' },
  { name: 'Slovakia', code: 'SK', region: 'Europe', flag: '🇸🇰' },
  { name: 'Slovenia', code: 'SI', region: 'Europe', flag: '🇸🇮' },
  { name: 'Solomon Islands', code: 'SB', region: 'Oceania', flag: '🇸🇧' },
  { name: 'Somalia', code: 'SO', region: 'Africa', flag: '🇸🇴' },
  { name: 'South Africa', code: 'ZA', region: 'Africa', flag: '🇿🇦' },
  { name: 'South Korea', code: 'KR', region: 'Asia', flag: '🇰🇷' },
  { name: 'South Sudan', code: 'SS', region: 'Africa', flag: '🇸🇸' },
  { name: 'Spain', code: 'ES', region: 'Europe', flag: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', region: 'Asia', flag: '🇱🇰' },
  { name: 'Sudan', code: 'SD', region: 'Africa', flag: '🇸🇩' },
  { name: 'Suriname', code: 'SR', region: 'Americas', flag: '🇸🇷' },
  { name: 'Sweden', code: 'SE', region: 'Europe', flag: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', region: 'Europe', flag: '🇨🇭' },
  { name: 'Syria', code: 'SY', region: 'Asia', flag: '🇸🇾' },
  { name: 'Taiwan', code: 'TW', region: 'Asia', flag: '🇹🇼' },
  { name: 'Tajikistan', code: 'TJ', region: 'Asia', flag: '🇹🇯' },
  { name: 'Tanzania', code: 'TZ', region: 'Africa', flag: '🇹🇿' },
  { name: 'Thailand', code: 'TH', region: 'Asia', flag: '🇹🇭' },
  { name: 'Timor-Leste', code: 'TL', region: 'Asia', flag: '🇹🇱' },
  { name: 'Togo', code: 'TG', region: 'Africa', flag: '🇹🇬' },
  { name: 'Tonga', code: 'TO', region: 'Oceania', flag: '🇹🇴' },
  { name: 'Trinidad and Tobago', code: 'TT', region: 'Americas', flag: '🇹🇹' },
  { name: 'Tunisia', code: 'TN', region: 'Africa', flag: '🇹🇳' },
  { name: 'Turkey', code: 'TR', region: 'Europe/Asia', flag: '🇹🇷' },
  { name: 'Turkmenistan', code: 'TM', region: 'Asia', flag: '🇹🇲' },
  { name: 'Tuvalu', code: 'TV', region: 'Oceania', flag: '🇹🇻' },
  { name: 'Uganda', code: 'UG', region: 'Africa', flag: '🇺🇬' },
  { name: 'Ukraine', code: 'UA', region: 'Europe', flag: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'AE', region: 'Asia', flag: '🇦🇪' },
  { name: 'Uruguay', code: 'UY', region: 'Americas', flag: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZ', region: 'Asia', flag: '🇺🇿' },
  { name: 'Vanuatu', code: 'VU', region: 'Oceania', flag: '🇻🇺' },
  { name: 'Vatican City', code: 'VA', region: 'Europe', flag: '🇻🇦' },
  { name: 'Venezuela', code: 'VE', region: 'Americas', flag: '🇻🇪' },
  { name: 'Vietnam', code: 'VN', region: 'Asia', flag: '🇻🇳' },
  { name: 'Yemen', code: 'YE', region: 'Asia', flag: '🇾🇪' },
  { name: 'Zambia', code: 'ZM', region: 'Africa', flag: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', region: 'Africa', flag: '🇿🇼' },
  { name: 'Global / Other', code: 'GL', region: 'Global', flag: '🌍' },
];

export const SCAM_PATTERNS = {
  urgency: [
    /urgent/i, /immediately/i, /action required/i, /final notice/i, /account blocked/i, 
    /suspended/i, /deadline/i, /security risk/i, /expired/i, /pending disconnection/i,
    /24 hours/i, /act now/i, /prevent closure/i
  ],
  reward: [
    /won/i, /lottery/i, /congratulations/i, /gift card/i, /cash prize/i, /unclaimed/i, 
    /reward/i, /winner/i, /jackpot/i, /draw/i, /rebate/i, /exclusive winner/i, /claim code/i
  ],
  bank: [
    /kyc/i, /bank/i, /hDFC/i, /sbi/i, /wells fargo/i, /character/i, /chase/i, /paypal/i, 
    /re-verify/i, /re-activate/i, /re-validate/i, /official alert/i
  ],
  otp: [
    /otp/i, /one-time password/i, /verification code/i, /do not share/i, /secure code/i,
    /authorise/i, /confirmation code/i
  ],
  links: [
    /\.xyz/i, /\.top/i, /\.click/i, /\.link/i, /bit\.ly/i, /t\.co/i, /tinyurl/i, 
    /\.info/i, /\.biz/i, /\.zip/i, /\.cam/i, /\.icu/i, /\.work/i
  ],
  job: [
    /part-time/i, /salary/i, /work from home/i, /job offer/i, /commission/i, /hiring/i, 
    /recruiting/i, /application/i, /hr/i, /weekly pay/i, /no experience/i, /daily salary/i,
    /telegram task/i, /whatsapp task/i, /easy income/i, /manager/i, /recruit/i
  ],
  delivery: [
    /delivery/i, /package/i, /parcel/i, /shipping/i, /courier/i, /track/i, /post/i, 
    /missed/i, /reschedule/i, /usps/i, /ups/i, /fedex/i, /dhl/i, /royal mail/i, 
    /evri/i, /postal/i, /warehouse/i, /customs fee/i, /unpaid postage/i, /held at depot/i
  ],
  securityAlert: [
    /unusual login/i, /verification required/i, /verify your account/i, /security alert/i, 
    /unauthorized access/i, /locked/i, /suspended/i, /compromised/i, /confirm identity/i, 
    /unusual activity/i, /new device/i, /sign-in alert/i, /suspicious sign-in/i
  ],
  crypto: [/crypto/i, /wallet/i, /bitcoin/i, /investment/i, /seed phrase/i, /airdrop/i, /mining/i, /binance/i, /ethereum/i, /blockchain/i, /profit guarantee/i],
  romance: [/sweetheart/i, /honey/i, /trust me/i, /meet you/i, /send money/i, /widow/i, /lonely/i],
  immigration: [/visa/i, /passport/i, /immigration/i, /customs/i, /border/i, /deportation/i, /green card/i],
  taxAuthority: [/irs/i, /hmrc/i, /revenue/i, /tax refund/i, /tax audit/i, /overdue tax/i, /cra/i, /income tax/i],
  techSupport: [/microsoft support/i, /apple support/i, /windows alert/i, /virus detected/i, /system infected/i, /mcafee/i, /norton/i],
  utilityScam: [/electricity bill/i, /water bill/i, /utility bill/i, /disconnection notice/i, /meter replacement/i],
};

export const FAQS: FAQItem[] = [
  {
    question: "What does this tool check?",
    answer: "ScamGuard analyzes text messages (SMS/WhatsApp), URLs (links), and screenshots to identify fraud patterns, phishing lures, and social engineering tactics."
  },
  {
    question: "Is this tool free to use?",
    answer: "Yes, ScamGuard Global is a 100% free community-driven security tool designed to help users worldwide stay safe from digital fraud."
  },
  {
    question: "Can I check messages, URLs, and images?",
    answer: "Absolutely. Our multi-mode engine supports pasting message text, scanning suspicious links, and forensic image analysis for screenshots."
  }
];

export const FAQ_TRANSLATIONS: Record<string, FAQItem[]> = {
  hi: [
    { question: "यह टूल क्या चेक करता है?", answer: "स्कैमगार्ड धोखाधड़ी पैटर्न, फिशिंग और सोशल इंजीनियरिंग युक्तियों की पहचान करने के लिए मैसेज, लिंक और स्क्रीनशॉट का विश्लेषण करता है।" },
  ]
};

export const TRANSLATION_DICTIONARY: Record<string, Record<string, string>> = {
  hi: {
    'HIGH RISK': 'उच्च जोखिम',
    'MEDIUM RISK': 'मध्यम जोखिम',
    'LOW RISK': 'कम जोखिम',
  }
};

export const SCAM_GALLERY_EXAMPLES = [
  {
    app: "PhonePe",
    platform: "UPI (India)",
    redFlags: ["Incorrect font weight on amount", "Missing transaction ID characters", "Irregular UI shadows"],
    fakeDesc: "Generated using a 'Screenshot Editor' app. Notice the slightly pixelated font on the ₹ amount.",
    realDesc: "Standard system font, clear alignment, and valid UTC timestamp."
  }
];
